name: DropChest
main: com.narrowtux.DropChest.DropChest
version: 0.7.7
author: narrowtux
description: DropChest sucks dropped loot into Chests. It's very useful if you do automatic farming or have mobs traps which gather the loot.
commands:
 dropchest:
  description: Access to all DropChest related commands
  aliases:
      - dc
 dcitem:
  description: Gives you the name or the id of the passed item.
  usage: /dcitem [NAME|id]
 chestinfo:
  description: Gives you information about a chests contents. Omit the argument and rightclick on a non-dropchest
  usage: /chestinfo {name|id}